//
// Created by solangel quiroga on 30/11/22.
//

#ifndef PROYECTO_PROGRAMACION2_MODODEJUEGO_H
#define PROYECTO_PROGRAMACION2_MODODEJUEGO_H

enum
class ModoDeJuego { INSTRUCCIONES, DOS_JUGADORES, UN_JUGADOR };

#endif //PROYECTO_PROGRAMACION2_MODODEJUEGO_H
